# Sentence.create!(content:"We are the champion", article_id: 1, position: 1, paragraph: 1)
# Sentence.create!(content:"In the world", article_id: 1, position: 2, paragraph: 1)
# Sentence.create!(content:"Take me to this place", article_id: 1, position: 3, paragraph: 1)
# Sentence.create!(content:"Let me down", article_id: 1, position: 4, paragraph: 1)
# Sentence.create!(content:"Thanks a lot", article_id: 1, position: 5, paragraph: 1)
Comment.create!(content:"That's greate", sentence_id: 2)
Comment.create!(content:"That's greate", sentence_id: 2)
Comment.create!(content:"That's greate", sentence_id: 2)
Comment.create!(content:"That's greate", sentence_id: 3)
Comment.create!(content:"That's greate", sentence_id: 3)
Comment.create!(content:"That's greate", sentence_id: 4)
Comment.create!(content:"That's greate", sentence_id: 4)
Comment.create!(content:"That's greate", sentence_id: 5)
Comment.create!(content:"That's greate", sentence_id: 5)